apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-web-app
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=yelb-ui,tier=frontend'
     app.kubernetes.io/part-of: tanzu-java-web-app-mathys
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: yelb
  dependsOn: [Component:yelb-appserver]
